### ISSUE TITLE
WQXtoPandas failure as URL has changed

### ISSUE THREAD

**Issue by mcooper12590** [speleophysics/olm#39]
When running runWQXtoPandas there is a failure assigning the WQX variable as there is no fetched XML file. The Sites.log.xml file shows that there was a failure to retrieve data from the USGS database:

<ErrorResponse><Error><Type></Type><Code></Code><Message></Message><Detail>
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist

The URL for fetching water chemistry data has changed from http://qwwebservices.usgs.gov/nwisqw/Result/ to http://waterqualitydata.us/Result/ . Changing the BASE_URL variable in the DataRetrieval.querySiteList to the new URL works.

**Comment by speleophysics** [comment]
changed base url and it works again now
